---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--exp
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--exp
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /gpfs/slac/cryo/fs1/exp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        #- key: kubernetes.io/hostname
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--exp
spec:
  storageClassName: cryoem-daq-dev--exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-exp
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--sdf-exp
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        #- key: kubernetes.io/hostname
        - key: storage/sdf
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-exp
spec:
  storageClassName: cryoem-daq-dev--sdf-exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi


---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem1
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem1
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem1-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem1-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem1
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1
spec:
  storageClassName: cryoem-daq-dev--tem1
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem1-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi


---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem2/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem2
          operator: In
          values:
          - 'true'

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem2-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem2-gainrefs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem2
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2
spec:
  storageClassName: cryoem-daq-dev--tem2
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem2-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem3
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem3/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem3
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem3-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem3-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem3
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3
spec:
  storageClassName: cryoem-daq-dev--tem3
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem3-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem4
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem4/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem4
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem4-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem4-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tem4
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4
spec:
  storageClassName: cryoem-daq-dev--tem4
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem4-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tembeta
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tembeta
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tembeta/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tembeta
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tembeta-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tembeta-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tembeta-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-tembeta
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tembeta
spec:
  storageClassName: cryoem-daq-dev--tembeta
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tembeta-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tembeta-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi


---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temalpha
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--temalpha
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/temalpha
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-temalpha
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temalpha-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--temalpha-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/temalpha-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-temalpha
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temalpha
spec:
  storageClassName: cryoem-daq-dev--temalpha
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temalpha-gainrefs
spec:
  storageClassName: cryoem-daq-dev--temalpha-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi



---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--fib1
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--fib1
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/fib1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-fib1
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--fib1
spec:
  storageClassName: cryoem-daq-dev--fib1
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temgamma
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--temgamma
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/temgamma/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-temgamma
          operator: In
          values:
          - 'true'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temgamma-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--temgamma-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/temgamma-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cryoem/storage-temgamma
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temgamma
spec:
  storageClassName: cryoem-daq-dev--temgamma
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--temgamma-gainrefs
spec:
  storageClassName: cryoem-daq-dev--temgamma-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

